/**
 * JOO-1792 / joori#2670: PRF and largeBlob WebAuthn extensions exist to transport the
 * wallet encryption secret. They must only be requested — and only be REQUIRED — when
 * wallet creation is enabled. With wallets disabled (the Joori deployment shape), a
 * passkey without PRF support must register and log in normally instead of freezing or
 * failing (previously the first-auth and login ceremonies requested prf unconditionally
 * and treated a missing secret as fatal, freezing the signup spinner after the account
 * had already been created server-side).
 */

const PRF_SALT = 'Alore';

export type WalletExtensionPurpose = 'registration' | 'first-auth' | 'login';

export interface WalletExtensionsRequest {
  prf?: { eval: { first: Uint8Array } };
  largeBlob?: { support: 'preferred' } | { write: Uint8Array } | { read: true };
}

export interface BuildWalletExtensionsOptions {
  /** largeBlob.write is only sent when exactly one credential is allowed (first-auth). */
  singleAllowCredential?: boolean;
  /** The random blob to write during first-auth; generated by the caller. */
  largeBlobWriteSecret?: Uint8Array;
}

/**
 * Build the WebAuthn extension request for a ceremony. Returns an empty object when
 * wallet creation is disabled so no PRF/largeBlob negotiation happens at all.
 */
export function buildWalletExtensions(
  purpose: WalletExtensionPurpose,
  enableWalletCreation: boolean,
  options: BuildWalletExtensionsOptions = {},
): WalletExtensionsRequest {
  if (!enableWalletCreation) {
    return {};
  }

  const prf = { eval: { first: new TextEncoder().encode(PRF_SALT) } };

  switch (purpose) {
    case 'registration':
      return { prf, largeBlob: { support: 'preferred' as const } };
    case 'first-auth': {
      const extensions: WalletExtensionsRequest = { prf };
      if (options.singleAllowCredential && options.largeBlobWriteSecret) {
        extensions.largeBlob = { write: options.largeBlobWriteSecret };
      }
      return extensions;
    }
    case 'login':
    default:
      return { prf, largeBlob: { read: true as const } };
  }
}

export interface ResolveWalletSecretOptions {
  /** The blob written during first-auth; required to recover the secret when Safari reports largeBlob.written. */
  largeBlobWriteSecret?: Uint8Array;
  isSafari?: boolean;
}

export interface WalletSecretResolution {
  /**
   * false only when wallets are enabled and the authenticator yielded neither a PRF
   * result nor a largeBlob result. True with no secret when wallets are disabled.
   */
  supported: boolean;
  secret?: Uint8Array;
}

/**
 * Resolve the wallet secret from a ceremony's client extension results. With wallets
 * disabled the outcome is always supported (no secret is needed or derivable). With
 * wallets enabled the previous semantics are preserved exactly, including the Safari
 * largeBlob workaround.
 */
export function resolveWalletSecret(
  enableWalletCreation: boolean,
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  extensionResults: any,
  options: ResolveWalletSecretOptions = {},
): WalletSecretResolution {
  if (!enableWalletCreation) {
    return { supported: true };
  }

  const prfSecret = extensionResults?.prf?.results?.first as Uint8Array | undefined;
  if (prfSecret) {
    return { supported: true, secret: prfSecret };
  }

  // first-auth (write mode): the secret is the blob we wrote, not a returned value.
  const blobWritten = !!extensionResults?.largeBlob?.written;
  if (blobWritten && options.largeBlobWriteSecret) {
    return { supported: true, secret: options.largeBlobWriteSecret };
  }

  // login (read mode): largeBlob.blob is the stored secret itself.
  const blobRead = extensionResults?.largeBlob?.blob as Uint8Array | undefined;
  if (blobRead) {
    return { supported: true, secret: blobRead };
  }

  // Safari quirk (preserved from the original implementation): it reports
  // largeBlob.written even when PRF produced the secret path above did not run.
  if (blobWritten && options.isSafari && options.largeBlobWriteSecret) {
    return { supported: true, secret: options.largeBlobWriteSecret };
  }

  return { supported: false };
}
