name: Linter

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]
  workflow_dispatch:

jobs:
  lint:
    name: Lint packages
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [alore-auth-ui, alore-crypto-sdk, alore-auth-sdk]
    defaults:
      run:
        working-directory: packages/${{ matrix.package }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'pnpm'
          cache-dependency-path: ${{ github.workspace }}/packages/${{ matrix.package }}/pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run ESLint
        run: pnpm -w run lint

      # - name: Run TypeScript Check
      #   run: pnpm -w run type-check

      - name: Check Formatting with Prettier
        run: pnpm -w run format-check
